#!/bin/bash

cd /var/canvas
# Crear usuario de la aplicacion
sudo adduser --disabled-password --gecos canvas $APP_USER

# Preparar ficheros y carpetas para generación de assets
mkdir -p log tmp/pids public/assets app/stylesheets/brandable_css_brands
touch app/stylesheets/_brandable_variables_defaults_autogenerated.scss
touch Gemfile.lock
touch log/production.log
sudo chown -R $APP_USER config/environment.rb log tmp public/assets \
                         app/stylesheets/_brandable_variables_defaults_autogenerated.scss \
                         app/stylesheets/brandable_css_brands Gemfile.lock config.ru
yarn install

# Compilar assets
RAILS_ENV=production bundle exec rake canvas:compile_assets
sudo chown -R $APP_USER public/dist/brandable_css

