#!/bin/bash

cd /var/canvas
CANVAS_LMS_ADMIN_EMAIL=jorgev.bo@gmail.com
CANVAS_LMS_ADMIN_PASSWORD=ifjorgev
CANVAS_LMS_ACCOUNT_NAME=Canvas
CANVAS_LMS_STATS_COLLECTION=3

DISABLE_DATABASE_ENVIRONMENT_CHECK=1

export CANVAS_LMS_ADMIN_EMAIL
export CANVAS_LMS_ADMIN_PASSWORD
export CANVAS_LMS_ACCOUNT_NAME
export CANVAS_LMS_STATS_COLLECTION
export DISABLE_DATABASE_ENVIRONMENT_CHECK

# RAILS_ENV=production bundle exec rake db:drop db:create

# RECREAR LA DB SI NO EXISTE
PGPASSWORD=$RDS_PASSWORD psql -h $RDS_ADDRESS -U $RDS_USERNAME -d postgres -c "DROP DATABASE IF EXISTS ${RDS_DBNAME};"
PGPASSWORD=$RDS_PASSWORD psql -h $RDS_ADDRESS -U $RDS_USERNAME -d postgres -c "CREATE DATABASE ${RDS_DBNAME} WITH OWNER ${RDS_USERNAME};"

# Ejecutar migrations
RAILS_ENV=production bundle exec rake db:initial_setup
