development:
  bucket_name: development-bucket
  access_key_id: access_key
  secret_access_key: secret_key
  region: us-east-1

test:
  bucket_name: test-bucket
  access_key_id: access_key
  secret_access_key: secret_key
  region: us-east-1
  
production:
  bucket_name: "<%= ENV['S3_BUCKET'] %>"
  access_key_id: "<%= ENV['AWS_ACCESS_KEY'] %>"
  secret_access_key: "<%= ENV['AWS_SECRET_KEY'] %>"
  region: "<%= ENV['REGION'] %>"